[models] Pydantic model Borrowed
ahsan-kamal-sdq/LibraryManagementSystem pull request #12
Opened 2023-04-25 09:55 UTC by mustansirMuz

Asana Task: https://app.asana.com/0/1204411152293714/1204439508142896

Added the pydantic model for Borrowed
Added the following validations:
- Due date must be greater than issue date
- Return date must be greater than Issue date

2023-04-25 11:43 UTC, mtalhatahir2001 requested changes
Config class is missing. That contains an example model to be shown in swagger docs.

2023-04-26 09:46 UTC, mustansirMuz commented
> Config class is missing. That contains an example model to be shown in swagger docs.

Added

2023-04-26 09:59 UTC, SohaibkhanFolio3 approved these changes

2023-04-26 10:37 UTC, Sana-Ullah786 approved these changes
Overall, everything seems perfect. ✨

2023-04-26 12:20 UTC, merged