[API]-Auth]  Logout
ahsan-kamal-sdq/LibraryManagementSystem pull request #24
Opened 2023-05-04 11:39 UTC by mustansirMuz

Asana Link: https://app.asana.com/0/1204411152293714/1204468697159511/f

- Implemented the logout functionality using redis (blacklist method) and have updated the readme for installation guide
- Added new env variables in the example which should be copied over to your local env file.

2023-05-04 13:52 UTC, mtalhatahir2001 approved these changes
LGTM

2023-05-05 12:21 UTC, Sana-Ullah786 requested changes

2023-05-05 12:21 UTC, Sana-Ullah786 commented on src/endpoints/auth.py
> +def get_jwt_exp(token):
Type annotations are missing.

2023-05-05 12:28 UTC, Sana-Ullah786 approved these changes
Approved. ✨.

2023-05-05 12:29 UTC, merged