Sohaib status model
ahsan-kamal-sdq/LibraryManagementSystem pull request #54
Opened 2023-05-16 09:58 UTC by SohaibkhanFolio3

Alembic Setup with respect of status is done , 
New Status_id column  replaces status column in Copy Table , 
status_id coming from status table now , table created . 
Tickets:
https://app.asana.com/0/1204411152293714/1204561574917319/f
https://app.asana.com/0/1204411152293714/1204468697159503/f
https://app.asana.com/0/1204411152293714/1204610448737250/f
https://app.asana.com/0/1204411152293714/1204593647129122/f

2023-05-17 08:07 UTC, mustansirMuz approved these changes
LGTM

2023-05-17 12:46 UTC, Sana-Ullah786 requested changes
No PUT method for status ?

2023-05-17 14:45 UTC, Sana-Ullah786 commented on src/endpoints/status/delete/status_delete.py
> +@router.get("/", status_code=status.HTTP_204_NO_CONTENT, response_model=None)
Fixed.

2023-05-17 15:03 UTC, Sana-Ullah786 commented on src/models/all_models.py
> +
Fixed.

2023-05-21 07:13 UTC, Sana-Ullah786 approved these changes
Approved. ✨

2023-05-21 07:15 UTC, merged